### PR TITLE
CLOUDP-70637: Update UsersService.Create to use the struct AtlasUser in the ops manager go client

### PR DESCRIPTION
**Pull request by andreaangiolillo**
## Proposed changes

_Jira ticket:_ CLOUDP-70637

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Comment by andreaangiolillo** [comment]
`AtlasUser` does not have the field `links []*Link`, I am going to add it in https://jira.mongodb.org/browse/CLOUDP-70640

**Review by gssbzn — COMMENTED** [review]
I don't know if I agree with this change, it would be confusing for users of the client why is it Atlas Users when this is ops manager
Does this change has to do with the create command? I'd think I'd rather let the cli handle the difference the same way we have atlas projects and ops manager projects given they're different

**Comment by andreaangiolillo** [comment]
It is for the command invite https://jira.mongodb.org/browse/CLOUDP-70011. If the problem is only the name we can rename `AtlasUser` to `User`, I don't think is a breaking change. I don't see why we should define another struct when we have the same in atlas.

**Comment by gssbzn** [comment]
@andreaangiolillo we can't rename it on the atlas client, that's a breaking change, a breaking change constitute any change that if I update to that new version of the client it means me having to change my existing use of the library, renaming structs/fields is always a breaking change

You have to consider as well that not all fields are the same between Atlas and Ops Manager, Atlas has country which Ops Manager does not and the difference can increase over time, again this is similar to how we have an Atlas project and an Ops Manager project because they have different fields

**Pull request closed without merging**
